#!/usr/bin/php
<?php
// #!/usr/bin/php -d xdebug.profiler_enable=On
$argv = $_SERVER['argv'];
$argc = $_SERVER['argc'];
if ($argc < 2) {
    exit;
}
elseif ($argc == 2 && $argv[1] == '-') {
    while ($line = trim(fgets(STDIN))) {
        $line = strip_dotdash($line);
        decode_txt($line);
    }
}
else {
    for ($i=1;$i<$argc;$i++ ) {
        $line = strip_dotdash($line);
        decode_txt($argv[$i]);
    }
}
function strip_dotdash($file) {
    if (substr($file, 0, 2) == './')
        $file = substr($file, 2);
    return $file;
}

function decode_txt($file) {
    if (file_exists($file)) {
        $txt = file_get_contents($file);
        echo utf8_decode(imap_qprint($txt));
    }
}
?>